services:
  xss:
    build: .
    env_file:
      - path: .env
        required: false
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
